name: Callable Build artefacts

on:
    workflow_dispatch:
        inputs:
            archive:
                description: archive artifacts name
                default: 'build_and_test'
                required: false
                type: string

jobs:
    build_artefacts:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Typescript repo
              id: action_ts_setup_repo
              uses: youwol-jdecharne/nestor/ts/set_up_repo@main
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Build typescript artefacts
              id: action_ts_build_artefact
              uses: youwol-jdecharne/nestor/ts/build_and_test@main
              with:
                  integrations: py-youwol
                  archive: ${{ inputs.archive }}
                  token: ${{ secrets.GITHUB_TOKEN }}
