name: Continuous Integration for Typescript

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - develop

jobs:
    build_artefacts:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Typescript repo
              id: action_ts_setup_repo
              uses: youwol-jdecharne/gh-actions/ts_set_up_repo@main
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Static analysis
              id: action_ts_static_analysis
              uses: youwol-jdecharne/gh-actions/ts_static_analysis@main

            - name: Build typescript artefacts
              id: action_ts_build_artefact
              uses: youwol-jdecharne/gh-actions/ts_build_artefacts@main
              with:
                  integrations: py-youwol
