name: Pull Request Checks

on:
    pull_request:
        branches:
            - main

jobs:
    integration:
        name: Integration with py-youwol
        runs-on: ubuntu-latest
        steps:
            - name: Prepare repository
              id: prepare
              uses: youwol/nestor/ts/prepare@v1

            - name: Run Tests with coverage
              id: tests_coverage
              uses: youwol/nestor/ts/tests_coverage@v1
              with:
                  py-youwol_conf_path: yw_config_IT.py
                  py-youwol_conf_repository: youwol/integrations-tests-conf
                  py-youwol_ref: ${{ inputs.py-youwol_ref }}

            - name: On Tests Failure
              id: on_tests_failure
              if: steps.tests_coverage.outputs.result == 'failure'
              uses: actions/github-script@v6
              with:
                  script: core.setFailed("Job failed because tests has failed, see job logs and annotations.")

    static_analysis:
        name: Static analysis
        runs-on: ubuntu-latest
        steps:
            - name: Prepare repository
              id: prepare
              uses: youwol/nestor/ts/prepare@v1

            - name: Static Analysis
              id: static_analysis
              uses: youwol/nestor/ts/static_analysis@v1

            - name: On Static Analysis Failure
              id: static_analysis_failure
              if: steps.static_analysis.outputs.result == 'failure'
              uses: actions/github-script@v6
              with:
                  script: core.setFailed("Job failed because static analysis has failed, see job logs and annotations.")
